name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod download

    - name: Run tests with coverage
      run: |
        go test -v -race -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-go-app:latest

    - name: Deploy to Kubernetes with Helm
      uses: azure/k8s-deploy@v1
      with:
        method: helm
        helm-version: '3.2.4'
        namespace: my-go-app
        chart: ./helm/my-go-app
        set: image.tag=latest
        kubeconfig: ${{ secrets.KUBECONFIG }}